baseURL: https://liouk.me
title: liouk.me
theme: charlolamode
copyright: "Â© 2018-2023 Ilias Rinis. All rights reserved."

menu:
    main:
      - name: About
        url: /about/
        weight: 30

params:
    author: Ilias Rinis
    defaultTheme: auto
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: false

    profileMode:
        enabled: true
        title: Ilias Rinis
        description: |
          MSc. ETH Zurich

          Dipl. Ing. CEID Patras

          Software Engineer at [*Red Hat*](https://redhat.com/)
        imageUrl: "/img/headshot.jpg"
        imageTitle: ilias
        buttons:

    socialIcons:
        - name: github
          url: "https://github.com/liouk"
        - name: linkedin
          url: "https://www.linkedin.com/in/iliasrinis/"
        - name: twitter
          url: "https://twitter.com/iliasrn"
        - name: email
          url: "mailto:hi@liouk.me"

    assets:
        favicon: "/img/favicon.ico"
        favicon16x16: "/img/favicon-16x16.png"
        favicon32x32: "/img/favicon-32x32.png"
        apple_touch_icon: "/img/apple-touch-icon.png"
        safari_pinned_tab: "/img/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
